<a href="https://colab.research.google.com/github/Janu2331/Machine-learning-/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy- Numeric Python
# Most powerful package - Library

#Numpy- Dimensions
# A-One Dimensionaal Array
# [A,B] || [ A
             #B ]-Two Dimensional Array- Row ||column
# Three Dimensional
# Array-Storing,Manipulating,Similar Data Type
# Faster than any mathematical functions
# Convenient compared to other packages
# Memory Efficiency
# Support Multi Dimensional Arrays
#speed(Numpy operations)>speed(Lists operations)
#size(Numpy operations)<size(Lists operations)
# memory optimizatin(Numpy)>memory optimization(List operations)

In [ ]:
# Install numpy - pip3 install numpy // pip install numpy

In [ ]:
import numpy as np

In [ ]:
# create a numpy array
#1D array
arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [ ]:
# creating 2D array - Matrix
arr2D = np.array([
    [0,0,0],[0,0,0]
])
print(arr2D)

[[0 0 0]
 [0 0 0]]


In [ ]:
allZeros=np.zeros((2,3))
print(allZeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
allOnes=np.ones((2,3))
print(allOnes)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
allConstant=np.full((2,3),6)
print(allConstant)

[[6 6 6]
 [6 6 6]]


In [ ]:

# Create an identity matrix - I - square Matrix
identity = np.eye(4)
print(identity)


# Identity Matrix - Aii = 1 && Aij = 0
# For all a Belongs to R MxN
#Aij -

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# creating random matrices


# between 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.81830377 0.34842037 0.38599123]
 [0.32224806 0.93954419 0.27037779]
 [0.97223162 0.34695251 0.51192815]]
[[13 15 19]
 [12 16 17]
 [11 15 16]]


In [ ]:
# Array properties
arr=np.array(([1,2,3,4],[2,3,4,5]))
print(arr)
# Shape of the array
print(f'The shape of the array is {arr.shape}')
# Size of array
print(f'The size of the array is {arr.size}')
#Datatype of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]
The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [ ]:
# Indexing and slicing


#Access the elements in 1D Array
arr = np.array([1,2,3,4,])
print(arr)
print(arr[3])

# Slicing the elements
print(arr[0:3])

# Access the element in 2D Array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr)
print(arr2[1,1])
print(arr2[0,:]) # First row with all the columns
print(arr2[:,0]) # First column with all the rows

[1 2 3 4]
4
[1 2 3]
[1 2 3 4]
3
[1 2 3]
[1 2]


In [ ]:
# l1 = []
# [l1.append(_) for _ in range(10)]
l1 = np.arange(10,-10,-3)

print(l1)

[10  7  4  1 -2 -5 -8]


In [ ]:
# Mathematcial operations
a=np.array([1,2,3])
b=np.array([3,4,5])
print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [ ]:
# Matrix multiplication
b1=np.array([[1,2,3],[2,3,4]])
b2=np.array([[5,6],[7,8],[1,3]])

# Dot product  ---- Product= AB -- A m x n -- B n x p
c = np.dot(b1,b2)
print(b1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]
