<a href="https://colab.research.google.com/github/Janu2331/Machine-learning-/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Recap
arr = np.array([[1,2,3],[4,5,6]])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr1=np.random.randint(1,2,(3,1))

In [5]:
arr.shape

(2, 3)

In [6]:
arr1.shape

(3, 1)

In [7]:
result=np.dot(arr,arr1)

In [8]:
print(result)

[[ 6]
 [15]]


In [9]:
r1=np.random.randint(10,20,(3,3))
print(r1)

[[18 17 10]
 [14 12 16]
 [19 15 16]]


In [10]:
r2=np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# r1 = I
result2=np.dot(r1,r2)

In [12]:
print(result2)

[[18. 17. 10.]
 [14. 12. 16.]
 [19. 15. 16.]]


In [13]:
t1=np.random.randint(3,6,(3,3))
t2=np.random.randint(3,6,(3,3))

In [ ]:
print(t1)
print(t2)

[[4 3 4]
 [4 5 3]
 [4 4 3]]
[[5 4 4]
 [5 3 3]
 [4 4 4]]


In [14]:
t3=t1+t2

In [15]:
print(t3)

[[6 9 7]
 [9 8 9]
 [6 7 7]]


In [16]:
#matrix multiplication
result=np.dot(arr,arr1)

In [17]:
# statistical operations
mean=t3.mean()
mode=t3.max()
median=np.median(t3)
std=np.std(t3)
var=np.var(t3)

In [18]:
print(mean)

7.555555555555555


In [19]:
print(mode)

9


In [20]:
print(median)

7.0


In [21]:
print(std)

1.1653431646335017


In [22]:
print(var)

1.3580246913580245


In [23]:
std*std

1.3580246913580247

In [24]:
#Trignometry functions
# sin(x)
#cos(x)
#Tan(x)-sin(x)/cos(x)
#cosec-1/sin(x)
#sec-1/cos(x)
#cot-1/tan(x)
angles = np.array([0,15,30,45,60,75,90])
#sin(array)
result=np.sin(np.radians(angles))
result1=np.cos(np.radians(angles))
result2=np.tan(np.radians(angles))

In [25]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [26]:
arr=np.array([1,2,3,4,5,6])
#Reshape the array
reshapedarr=arr.reshape(3,2)
print(reshapedarr)
flattendarr=arr.flatten()
print(flattendarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [27]:

#Stacking the data
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

#vertical stacking
arr3=np.vstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")

#Horizantal stacking
arr4=np.hstack((arr1,arr2))
print(f"The shape of the arr4 is {arr4.shape}")
print(arr4)

The shape of arr3 is (2, 4)
The shape of the arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [28]:
#Flitering
arr=np.array([10,20,30,40,50,60,70,80,90])
farr=arr[arr>40]
print(farr)

[50 60 70 80 90]
